# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BfHG3R-L6wazpUm64dJDNah0q4-DbyY
"""

# print numbers 1 to 100
for i in range(1, 101):
    print(i)

# countdown using while
count = 5
while count > 0:
    print("timer:", count)
    count -= 1

# break and continue
for i in range(1, 10):
    if i == 5:
        continue
    if i == 8:
        break
    print(i)

# iterate string
name = "python"
for ch in name:
    print(ch)

# multiplication table
num = 5
for i in range(1, 11):
    print(num, "x", i, "=", num * i)

# range with step
for i in range(0, 21, 2):
    print(i)